services:
  netcen-spring-2025:
    build:
      context: .
      dockerfile: Dockerfile
    image: netcen-pa2-image
    volumes:
      - ./Code:/home/netcen_pa2
    user: root
    container_name: netcen_pa2
    entrypoint: /bin/bash
    stdin_open: true
    tty: true