name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t netcen-pa2-image .

      - name: Run TestHarness.py Inside Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/Code:/home/netcen_pa2 \
            netcen-pa2-image python3 /home/netcen_pa2/TestHarness.py
