name: Test Reliable Transport

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Debug file structure
        run: ls -R

      - name: Check for reliable_transport.py
        run: |
          if [ ! -f reliable_transport.py ]; then
            echo "reliable_transport.py is missing"
            exit 1
          fi

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi

      - name: Run tests
        run: python3 Code/TestHarness.py
